/**
 * Helper function to generate Vite aliases for all @xndrjs workspace packages.
 * Reads from vite-aliases.generated.json generated by generate-workspace-config.ts
 *
 * Usage in vite.config.ts:
 * ```typescript
 * import { getWorkspaceAliases } from '../../scripts/vite-workspace-aliases';
 * import path from 'path';
 * import { fileURLToPath } from 'url';
 *
 * const __dirname = path.dirname(fileURLToPath(import.meta.url));
 * const workspaceAliases = getWorkspaceAliases(__dirname);
 *
 * export default defineConfig({
 *   resolve: {
 *     alias: {
 *       ...workspaceAliases,
 *       // other aliases
 *     }
 *   }
 * });
 * ```
 */

import { readFileSync, existsSync } from "fs";
import { join, resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Generates Vite alias configuration for all @xndrjs workspace packages.
 * Reads from vite-aliases.generated.json (generated by generate-workspace-config.ts).
 * Returns a map of package names to their source directory paths.
 *
 * @param configFileDir - The directory where vite.config.ts is located (used to resolve root)
 * @returns Record of package name to resolved source path
 */
export function getWorkspaceAliases(
  _configFileDir: string,
): Record<string, string> {
  // Find root directory by going up from scripts/ directory
  const rootDir = resolve(__dirname, "..");

  // Read aliases map from generated JSON
  const aliasesMapPath = join(__dirname, "vite-aliases.generated.json");
  let aliasesMap: Record<string, string> = {};

  try {
    const aliasesMapContent = readFileSync(aliasesMapPath, "utf-8");
    aliasesMap = JSON.parse(aliasesMapContent);
  } catch (error) {
    console.warn(
      `Warning: Could not read vite-aliases.generated.json at ${aliasesMapPath}.`,
      "Run 'pnpm generate:workspace-config' to generate it.",
    );
    return {};
  }

  // Convert directory names to absolute paths
  // Only include packages that have a src directory
  const aliases: Record<string, string> = {};
  for (const [pkgName, pkgDir] of Object.entries(aliasesMap)) {
    const srcPath = resolve(rootDir, "packages", pkgDir, "src");
    if (existsSync(srcPath)) {
      aliases[pkgName] = srcPath;
    }
  }

  return aliases;
}

